spring:
  application:
    name: fallinlove-account
    #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.170.146:8848
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    #服务器
    url: jdbc:mysql://xx.xx.xxx.xxx:3306/fallinlove?useUnicode=true&useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true
    #本地
    #url: jdbc:mysql://127.0.0.1:3306/fallinlove?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: 1qaz#EDC
  # redis
  redis:
    host: xx.xx.xxx.xxx
    port: 6379
    password: pass@123
    timeout: 2000 #超时连接
    lettuce:
      pool:
        max-idle: 4 #最大空闲数
        max-active: 4 #最大连接数
        min-idle: 0 #最小空闲数
  #mybatis-plus
  mybatis-plus:
    mapper-locations: classpath:com/max/fallinlove/account/mapper/xml/*.xml
    type-aliases-package: com.max.fallinlove.account.entity

server:
  port: 8082
  error:
    include-stacktrace: always

logging:
  level:
    org:
      springframwork:
        web: trace

# swagger 可使用
springfox:
  documentation:
    swagger-ui:
      enabled: true



