spring:
  application:
    name: fallinlove-gateway
    #nacos
  cloud:
    nacos:
      discovery:
        server-addr: 121.5.170.146:8848
    gateway:
      discovery:  #是否与服务发现组件进行结合，通过 serviceId(必须设置成大写) 转发到具体的服务实例。默认为false，设为true便开启通过服务中心的自动根据 serviceId 创建路由的功能。
        locator:  #路由访问方式：http://Gateway_HOST:Gateway_PORT/大写的serviceId，其中微服务应用名默认大写访问。
          enabled: true
          lower-case-service-id: true #使用小写的serviceId,同时一定要配置StripPrefix=1
      routes:
        - id: fallinlove-account
          uri: lb://fallinlove-account
          predicates:
            - Path=/account/**
          filters:
            #todo 降级配置
            #限流配置
            #- name: RequestRateLimiter
            #  args:
            #    redis-rate-limiter.replenishRate: 3 # 每秒允许处理的请求数量
            #    redis-rate-limiter.burstCapacity: 5 # 每秒最大处理的请求数量
            #    key-resolver: "#{@ipKeyResolver}" # 限流策略，对应策略的Bean
            - StripPrefix=1
        - id: fallinlove-finance
          uri: lb://fallinlove-finance
          predicates:
            - Path=/finance/**
          filters:
            #todo 降级配置
            #限流配置
            #- name: RequestRateLimiter
            #  args:
            #    redis-rate-limiter.replenishRate: 3 # 每秒允许处理的请求数量
            #    redis-rate-limiter.burstCapacity: 5 # 每秒最大处理的请求数量
            #    key-resolver: "#{@ipKeyResolver}" # 限流策略，对应策略的Bean
            - StripPrefix=1
      default-filters:
        - DedupeResponseHeader=Vary Access-Control-Allow-Credentials Access-Control-Allow-Origin, RETAIN_UNIQUE
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_FIRST
    # redis
  redis:
    host: 121.5.170.146
    port: 6379
    password: pass@123
    timeout: 2000 #超时连接
    lettuce:
      pool:
        max-idle: 4 #最大空闲数
        max-active: 4 #最大连接数
        min-idle: 0 #最小空闲数
    # DataSource Config
  datasource:
   driver-class-name: com.mysql.cj.jdbc.Driver
    #服务器
   url: jdbc:mysql://121.5.170.146:3306/fallinlove?useUnicode=true&useSSL=false&characterEncoding=utf8
    #本地
   #url: jdbc:mysql://127.0.0.1:3306/fallinlove?useUnicode=true&useSSL=false&characterEncoding=utf8
   username: root
   password: 1qaz#EDC
    #mybatis-plus
  mybatis-plus:
    mapper-locations: classpath:com/max/fallinlove/account/mapper/xml/*.xml
    type-aliases-package: com.max.fallinlove.account.entity

server:
  port: 8081
  error:
    include-stacktrace: always

logging:
  level:
    org:
      springframwork:
        web: trace



